name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the app
        run: ./gradlew build

      - name: Sign debug apk with debug key
        if: ${{ env.KEGBOT_DEBUG_KEYSTORE != '' }}
        uses: ilharp/sign-android-release@v2
        id: sign_debug_apk
        with:
          releaseDir: kegtab/build/outputs/apk/debug
          signingKey: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
          keyAlias: kegbot-debug
          keyStorePassword: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}
        env:
          KEGBOT_DEBUG_KEYSTORE: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
          ANDROID_SIGNING_KEY: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
          ANDROID_KEY_ALIAS: kegbot-debug
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}

      - name: Archive signed debug APK
        if: ${{ env.KEGBOT_DEBUG_KEYSTORE != '' }}
        uses: actions/upload-artifact@v4
        env:
          KEGBOT_DEBUG_KEYSTORE: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
        with:
          name: kegtab-debug-signed
          path: ${{ steps.sign_debug_apk.outputs.signedFile }}

      - name: Archive unsigned debug APK
        if: ${{ env.KEGBOT_DEBUG_KEYSTORE == '' }}
        uses: actions/upload-artifact@v4
        env:
          KEGBOT_DEBUG_KEYSTORE: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
        with:
          name: kegtab-debug-unsigned
          path: kegtab/build/outputs/apk/debug/*.apk

      - name: Sign release apk with debug key
        if: ${{ env.KEGBOT_DEBUG_KEYSTORE != '' }}
        uses: ilharp/sign-android-release@v2
        id: sign_release_apk
        with:
          releaseDir: kegtab/build/outputs/apk/release
          signingKey: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
          keyAlias: kegbot-debug
          keyStorePassword: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}
        env:
          KEGBOT_DEBUG_KEYSTORE: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
          ANDROID_SIGNING_KEY: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
          ANDROID_KEY_ALIAS: kegbot-debug
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEGBOT_DEBUG_KEYSTORE_PASSWORD }}

      - name: Archive signed release APK
        if: ${{ env.KEGBOT_DEBUG_KEYSTORE != '' }}
        uses: actions/upload-artifact@v4
        env:
          KEGBOT_DEBUG_KEYSTORE: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
        with:
          name: kegtab-release-signed
          path: ${{ steps.sign_release_apk.outputs.signedFile }}

      - name: Archive unsigned release APK
        if: ${{ env.KEGBOT_DEBUG_KEYSTORE == '' }}
        uses: actions/upload-artifact@v4
        env:
          KEGBOT_DEBUG_KEYSTORE: ${{ secrets.KEGBOT_DEBUG_KEYSTORE }}
        with:
          name: kegtab-release-unsigned
          path: kegtab/build/outputs/apk/release/*.apk
